version: "3.8"

services:
  ionic:
    image: node:18
    container_name: ionic-app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - "8100:8100"
    command: sh -c "npm install && npm install -g @ionic/cli && ionic serve --host=0.0.0.0 --port=8100 --disable-host-check"
